Repository hctnm2/OpenSourceEnthusiast, pull requests merged in 2022-10, with the labels that each got.

#1 Codes for Bank Management System Project
  codes/Bank_Management_CPP.cpp
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#2 Create wordGame.py
  codes/wordGame.py
Labels: hacktoberfest-accepted, hacktoberfest

#4 Doing My Part.
  codes/Joke_Generator.py
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#6 Doing My Part.
  codes/Calculator.py
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#3 Added a Selection Sort program in C++
  codes/SelectionSort.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#5 Added Calculator Project
  Projects/Calculator/calculator.css
  Projects/Calculator/index.html
  Projects/Calculator/script.js
  Projects/Calculator/style.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#7 Create RockPaperScissorsGame.py
  codes/RockPaperScissorsGame.py
Labels: hacktoberfest-accepted, hacktoberfest

#8 Patch 1
  codes/Reverse-Array.js
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#9 Dice rolling added
  codes/Dice_Rolling.py
Labels: hacktoberfest-accepted, hacktoberfest

#16 Patch 1
  codes/BMICalc.py
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#11 #light
  codes/oddeven.c
Labels: hacktoberfest-accepted, hacktoberfest

#13 added binary search program
  codes/binary_search.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#15 added linear search program
  codes/linear.c
Labels: hacktoberfest-accepted, hacktoberfest

#18 adding ascending.py on codes
  codes/ascending.py
Labels: hacktoberfest-accepted

#19 # real yagami 1
  codes/hangman.c
Labels: hacktoberfest-accepted

#20 #real yagami 1
  codes/fibonacci.cpp
Labels: hacktoberfest-accepted

#25 Create HeapSort.java
  codes/HeapSort.java
Labels: good first issue, hacktoberfest-accepted

#26 Create RadixSort.py
  codes/RadixSort.py
Labels: good first issue, hacktoberfest-accepted

#30 Create countdown.py
  codes/countdown.py
Labels: good first issue, hacktoberfest-accepted

#32 #real yagami 3 Create pigenhole.c
  pigenhole.c
Labels: good first issue, hacktoberfest-accepted

#36 real yagami 6 Create http-req-axios.js
  codes/http-req-axios.js
Labels: good first issue, hacktoberfest-accepted

#51 ci(Mergify): configuration update
  .mergify.yml
Labels: ci

#40 Create BST_Left_View.cpp
  codes/BST_Left_View.cpp
Labels: good first issue, hacktoberfest-accepted

#41 Create php_mysqli_create_table.php
  codes/Reverse_a_path_in_BST_using_queue.cpp
  codes/php_mysqli_create_table.php
Labels: good first issue, hacktoberfest-accepted

#38 Create Binary-Search.cpp
  codes/Binary-Search.cpp
Labels: good first issue, hacktoberfest-accepted

#42 Create fibonanci.c
  codes/fibonanci.c
Labels: good first issue, hacktoberfest-accepted

#44 Create bday_calc.py
  codes/bday_calc.py
Labels: good first issue, hacktoberfest-accepted

#45 Create bubble_sort.py
  codes/bubble_sort.py
Labels: good first issue, hacktoberfest-accepted

#46 Create linear_srch.py
  codes/linear_srch.py
Labels: good first issue, hacktoberfest-accepted

#47 Create music_player.py
  codes/music_player.py
Labels: good first issue, hacktoberfest-accepted

#48 Create print_argument.py
  codes/print_argument.py
Labels: good first issue, hacktoberfest-accepted

#49 Create cel2far.py
  codes/cel2far.py
Labels: good first issue, hacktoberfest-accepted

#50 Fibonacci series in java
  codes/fibo.java
Labels: good first issue, hacktoberfest-accepted

#78 ci(Mergify): configuration update
  .mergify.yml
Labels: good first issue, hacktoberfest-accepted

#79 Added python insertion sorting algorithm
  codes/insertion_sort.py
Labels: hacktoberfest-accepted
